name: Deployment Pipeline

on:
  push:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      rollback:
        description: 'Set to true to rollback to the previous deployment'
        required: false
        default: 'false'
      deploy:
        description: 'Set to true to deploy the current version'
        required: false
        default: 'true'

jobs:
  deploy:
    if: github.event.inputs.rollback != 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Get the current version
        id: get_version
        run: echo "VERSION=$(cat package.json | jq -r .version)" >> $GITHUB_ENV

      - name: Tag the version
        run: |
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          body: Release of version v${{ env.VERSION }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Deploy to server
  #       if: github.event.inputs.deploy == 'true' || github.event_name == 'release'
  #       env:
  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #         SSH_USER: ${{ secrets.SSH_USER }}
  #         SSH_HOST: ${{ secrets.SSH_HOST }}
  #       run: |
  #         ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST "
  #         cd /path/to/your/project &&
  #         git pull &&
  #         npm install &&
  #         npm run build &&
  #         pm2 restart all &&
  #         echo '$(git rev-parse HEAD)' > ~/.last_deploy_version"

  # rollback:
  #   if: github.event.inputs.rollback == 'true'
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Rollback to previous version
  #       env:
  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #         SSH_USER: ${{ secrets.SSH_USER }}
  #         SSH_HOST: ${{ secrets.SSH_HOST }}
  #       run: |
  #         ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST "
  #         cd /path/to/your/project &&
  #         git checkout $(cat ~/.last_deploy_version) &&
  #         npm install &&
  #         npm run build &&
  #         pm2 restart all"
