name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'


      - name: Get the current version
        id: get_version
        run: echo "VERSION=$(cat package.json | jq -r .version)" >> $GITHUB_ENV

      - name: Create new tag
        id: new_tag
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
            if [ -z "$latest_tag" ]; then
              new_tag=v${{ env.VERSION }}
            else
              new_version=$(echo $latest_tag | awk -F. '{print $NF+1}')
              new_tag=v${{ env.VERSION }}.$new_version
            fi
            echo "NEW_TAG=$new_tag" >> $GITHUB_ENV
            git tag $new_tag
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git $new_tag

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          body: Release of version v${{ env.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          