name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Secrets
        run: |
          echo "SSH_USER: ${{ secrets.SSH_USER }}"
          echo "EC2_HOST: ${{ secrets.EC2_HOST }}"

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$EC2_HOST "
          cd /home/ubuntu/ &&
          git pull origin main &&
          npm install &&
          npm run build &&
          pm2 restart all"
